### PR TITLE
summarize recent tool errors

### PR DESCRIPTION
**Pull request by jmchilton**
Trying to imagine queries that could point us to likely broken tools in some systematic way. Is this a fine approach?

Haven't actually run these to produce documentation yet, need to find a real server...

### CODE REVIEW

**Comment by erasche** [comment]
Hey @jmchilton these looks like a great idea :)

The queries need to be added to `parts/`, I'll update your PR to match that, and will run against EU for some example data.

**Comment by erasche** [comment]
> tools whose first execution is in recent weeks

As of now, the select just looks for tools which have executed in recent weeks? Is that the intention? Did you really want tools which have been run for the first time? We could do something like

```sql
SELECT tool_id
FROM job j
GROUP BY j.tool_id
HAVING min(j.create_time) > (now() - '1 weeks'::INTERVAL);
```

Currently:

```sql
SELECT tool_id
FROM job j
WHERE j.create_time > (now() - '$weeks weeks'::interval)
GROUP BY j.tool_id
```

**Comment by erasche** [comment]
I use https://sqlfum.pt/ for reformatting for readability, in case it is useful to you.

**Comment by jmchilton** [comment]
Thanks for the help, really appreciate it. I'm usually so good about this but my branch had diverged from yours (https://github.com/jmchilton/gxadmin/tree/tool_errors_2) - I'm going to try to go through and synchronize that with your changes - this probably explains why the queries didn't make a lot of sense and some didn't work. 

@natefoo felt these queries were misguided for dumping into influx since they were already aggregated - though they already produced some interesting and useful data when applied to main manually. He felt we should be generating this ourselves in grafana if we could somehow just dump the raw jobs and related tables into influx. I couldn't find anyway to keep influx insync with postgres tables and grafana seems fairly easy to attach to postgres directly (https://grafana.com/docs/features/datasources/postgres/) but I'm not sure @natefoo was comfortable with that. Things seem to be at an impasse.

**Comment by erasche** [comment]
@natefoo has a good point about the pre-aggregation. I've considered this a couple of times and not come up with anything good for it. There are a couple of other queries where I'd like to know e.g. "# of unique users running jobs in last 4 weeks", but putting that into influx is a bit strange and have to ensure the user doesn't try and aggregate that over non-4 week intervals as it would become meaningless.

I can definitely see pulling from postgres as a compromise there, just makes things a bit gross. I really liked the cleanliness in the setup of making complex analytics type postgres queries and sticking that into influx for high-volume querying. Impasse indeed.

**Comment by jmchilton** [comment]
Is the concern hitting our postgres server to hard or just a distaste for not using influx? And do the two of you (@erasche , @natefoo ) have the same concern?

**Comment by erasche** [comment]
It just feels weird to me? I had a very hardcoded image of live database → run analytics → TS database for analytics queries

I don't have a concrete argument against it, and any I can think of there are obvious solutions existing:

- grafana having postgres credentials - we could set up separate security credentials/etc.
- too much load on server - pgbouncer or readonly replicate of db (ok, that's not as easy of a solution to implement)

would also want to be sure that only authorized queries are passed through grafana's querying interface.

**Comment by natefoo** [comment]
Preferably we'd have this in Influx since its entire purpose is time series data and aggregating for viewing windows. Maybe Postgres could do this efficiently, I don't know.

The main problem with getting in to Influx is knowing what to start from. You can keep a list of all the terminal jobs you've already inserted but that's slow. You can have Galaxy report job completions directly (to statsd?). If we made sure that all jobs eventually made it to a terminal state we could at least have a rolling cutoff where we know that all jobs beyond a certain ID have already been dumped to Influx.

Or... ?

**Comment by erasche** [comment]
> You can keep a list of all the terminal jobs you've already inserted but that's slow

considered the same things for GRT, didn't come up with anything brilliant there either.

**Comment by erasche** [comment]
@natefoo at the risk of data not being fresh enough, we could do something like "oldest non-terminal job", and then just pull data up to that point?

**Comment by erasche** [comment]
Ugh paused jobs

**Comment by natefoo** [comment]
This shouldn't prevent merging and wasting John's good work, I'll think more about a solution.

**Comment by jmchilton** [comment]
This is still WIP - I need to redo the example data and re-fix the partial handling which I've finally figured out but haven't re-fixed.

Thanks for the comments all - good things to consider even if we don't have any good answers yet.

**Comment by erasche** [comment]
We should also tag based on handler + destination.

Today I caught an issue where 3 of my 12 handlers failed (on start, 6 days ago) to load a specific tool. The other 9 handlers loaded (and ran) the tool just fine. It'd be nice to be able to easily see that ok the vast majority (10x more) are related to 3 handlers.

**Comment by erasche** [comment]
@jmchilton I think this is a useful query even with the "windowed" aspect. I would like to merge this since the issue that was raised will not be solved any time soon, and I do like this incremental improvement.

With the issue I mentioned in my comment just now, I think I might be able to more quickly detect these (with a small window), so, I want this :)

Would you be willing to move out of WIP? I'll do any final updates / formatting crap.

**Comment by jmchilton** [comment]
@erasche I don't have the throughput right now to make progress on this I think, but I would ❤️ you taking over and getting this across the finish line in whatever form. Tasty beverage of your choice next month if you can get this merged despite the shitty state I left it in.

**Comment by erasche** [comment]
Awesomesauce, sounds good :) Save your bandwidth for more important things for sure.

**Comment by erasche** [comment]
Thanks so much @jmchilton!

**Comment by jmchilton** [comment]
I owe you, I mean I already did but now even more so, thanks so much @erasche!

**Pull request merged**
