### PR TITLE
Add query for Galaxy workers

### PR DESCRIPTION
**Pull request by selten**

### CODE REVIEW

**Comment by hexylena** [comment]
- this only works on 20.01+ due to pid column
- please add to the changelog
- please run `make` and commit any changes.

**Comment by hexylena** [comment]
Could you add a note in the help mentioning that it requires 20.01+? I guess people don't look in the changelog if their query fails.

**Comment by selten** [comment]
@hexylena should be done now.

**Comment by hexylena** [comment]
Looks great, thanks @selten!

**Pull request merged**
