### PR TITLE
Allow specific slurps to be used for slurping data

### PR DESCRIPTION
**Pull request by selten**
Allows the `gxadmin meta slurp` functions to specify which function they want to slurp.
This feature can be used if an initial slurp has been done already and you just want to append this with new queries. This could also be used in case a bug is discovered with other slurp queries.

### CODE REVIEW

**Comment by erasche** [comment]
I'm on the fence a little bit about this for now. I might want to look into a different implementation. In short term you can always add to `local` functions, in long term this seems sensible to implement.

**Comment by selten** [comment]
Well, I'd just like a feature (or similar) in gxadmin so I don't have to slurp again

**Comment by erasche** [comment]
@selten could you test this option for me?

**Comment by selten** [comment]
Have done so, also resolved the merge conflicts while at it.

**Comment by erasche** [comment]
Great!

**Comment by erasche** [comment]
No worries for resolving future merge conflicts. I'm trying to find away around it but since those are 'compiled', can just re-compile once merged.

**Pull request merged**
