### PR TITLE
Add "weeks" option to tool-usage query

### PR DESCRIPTION
**Pull request by natefoo**

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks Nate!

**Comment by erasche** [comment]
Err, @bgruening this shouldn't've been merged. @natefoo the script has been split into separate parts. I'll make the change but in the future you can make your changes in the parts/ directory and then run `make` to rebuild the gxadmin script + update any help text changes.

**Comment by erasche** [comment]
Fixed in 4392478e331a3bfc31526dd39d882237b45d0939

**Comment by natefoo** [comment]
@erasche thanks and sorry for the mistake. This is really turning in to quite a mature project! Really exciting.

**Comment by erasche** [comment]
Nurries mate, all good. Exciting, horrifying, one of the two.

Op di 2 apr. 2019 17:33 schreef Nate Coraor <notifications@github.com>:

**Pull request merged**
