### PR TITLE
#8 Add the information for a list of job ids

### PR DESCRIPTION
**Pull request by selten**
currently this only gives information on which host the job ran on, how long it ran for and the total memory consumption.

### CODE REVIEW

**Comment by erasche** [comment]
I'd like to restructure this if it's ok with you, I'd like to either accept:

- a list of IDs on the CLI (separated by spaces)
- or `-` to read from stdin

Currently nothing reads from files like that (except influx and that's an exception). Is that ok with you?

**Comment by selten** [comment]
> 
> 
> I'd like to restructure this if it's ok with you, I'd like to either accept:
> 
>     * a list of IDs on the CLI (separated by spaces)
> 
>     * or `-` to read from stdin
> 
> 
> Currently nothing reads from files like that (except influx and that's an exception). Is that ok with you?

Sure.
I just went by what your issue https://github.com/usegalaxy-eu/gxadmin/issues/8 had as idea, newline separated for the IDs, I agree that spaces would probably be better (or STDIN, but didn't know how to do that one).

**Comment by erasche** [comment]
Oh right this is for #8! Of course. Ok I'll add it really quick, I'm excited for this function :)

**Comment by erasche** [comment]
I pushed the changes, it's really easy to read from stdin into a variable, just `x=$(cat)` or `x=$(cat | paste -s -d' ')` if you need them space (or comma) separated.

**Comment by erasche** [comment]
Awesome, this will be super useful! Thanks @selten!

**Pull request merged**
