### PR TITLE
Add "time" modifier to "query" and "meta" functions for obtaining timing

### PR DESCRIPTION
**Pull request by natefoo**
Output for queries is in standard `query` format.

### CODE REVIEW

**Comment by natefoo** [comment]
Don't merge, I have an idea.

**Comment by natefoo** [comment]
Ok, I changed things so that any command can be prefixed with "time" to get time output. This allows getting the time of individual executions inside a function.

I'm not sure if you'll like the implementation though (e.g. it uses a global) so I left the old changes in the first commit rather than squashing and can revert if you prefer.

**Comment by erasche** [comment]
A global! :scream: :scream: :scream: 

Ohhhhh nooo. How will we ever survive being able to time everything rather than just some things.

**Comment by natefoo** [comment]
Well you basically weren't using globals anywhere else so I felt bad introducing the first one. :stuck_out_tongue_winking_eye:

**Pull request merged**
