### PR TITLE
Add a query for summary of queue grouped by destination and state

### PR DESCRIPTION
**Pull request by natefoo**
There is probably already a function that does this that I missed 😆

### CODE REVIEW

**Comment by bgruening** [comment]
Should we add a parameter to `gxadmin query queue-details` to group results?

**Comment by natefoo** [comment]
`queue-details` returns a lot of ungrouped information: job id, tool id, handler, time since creation, username, etc. so the grouped vs. ungrouped versions of the command would return vastly different information. What about `queue`, which only returns tool id, state, and count?

**Comment by bgruening** [comment]
queue sounds good!

**Comment by hexylena** [comment]
I've made it a bit more generic, but overall this looks good @natefoo, thanks for the contribution.

**Pull request merged**
